{{- if .Values.pdb.enabled }}
{{- if semverCompare "<1.21-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: "policy/v1beta1"
{{- else -}}
apiVersion: "policy/v1"
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "fhir-access-proxy.fullname" . }}
  labels:
    {{- include "fhir-access-proxy.labels" . | nindent 4 }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fhir-access-proxy.selectorLabels" . | nindent 6 }}
{{- end }}
